export const userActions={
    LOGIN:'LOGIN',
    LOGOUT:'LOGOUT',
    INIT_USER:'INIT_USER',
    FETCH_USER:'FETCH_USER'
}
export const noticeActions={
    LOAD_NOTICE_PAGE:'LOAD_NOTICE_PAGE',
    ADD_NEW_NOTICE_RECORD:'ADD_NEW_NOTICE',
    MARK_READ_ALL_NOTICE:'MARK_READ_ALL_NOTICE'
}
export const e2eeActions={
    INIT_E2EE:'INIT_E2EE',
    FETCH_PUBLIC_KEY:'FETCH_PUBLIC_KEY',
    UPLOAD_PUBLIC_KEY:'UPLOAD_PUBLIC_KEY',
    SET_PRIVATE_KEY:'SET_PRIVATE_KEY'
}
export const wsActions={
    INIT_WS:'INIT_WS',
    HANDLER_WS_OPEN:'HANDLER_WS_OPEN',
    HANDLER_WS_MESSAGE:'HANDLER_WS_MESSAGE',
    HANDLER_WS_ERROR:'HANDLER_WS_ERROR',
    HANDLER_WS_CLOSE:'HANDLER_WS_CLOSE',
    HANDLER_WS_RECONNECT:'HANDLER_WS_RECONNECT',
    HANDLER_WS_SEND:'HANDLER_WS_SEND',
    COMMIT_MESSAGE:'COMMIT_MESSAGE'
}
export const settingActions={
    INIT_SETTING:'INIT_SETTING',
    INIT_CHAT_SETTING:'INIT_CHAT_SETTING',
    UPDATE_CHAT_SETTING_ALLOW:'UPDATE_CHAT_SETTING_ALLOW',
    UPDATE_CHAT_SETTING_PINNED:'UPDATE_CHAT_SETTING_PINNED',
}
export const chatActions={
    INIT_CHAT:'INIT_CHAT',
    LOAD_CHAT_PAGE:'LOAD_CHAT_PAGE',
    ADD_NEW_CHAT_RECORD:'ADD_NEW_CHAT_RECORD',
    DELETE_CHAT_RECORD:'DELETE_CHAT_RECORD',
    LEAVE_CONVERSATION:'LEAVE_CONVERSATION',
    READ_CONVERSATION:'READ_CONVERSATION',
}