export const userMutations= {
    SET_USER:'SET_USER',
    CLEAR_USER:'CLEAR_USER',
    SET_USER_LIST:'SET_USER_LIST',
    SET_USER_TO_LIST:'PUSH_USER_TO_LIST',
    CLEAR_USER_LIST:'CLEAR_USER_LIST',
}
export const noticeMutations={
    ADD_CHIRPER_NOTICE:'ADD_CHIRPER_NOTICE',
    ADD_TWEETED:'ADD_TWEETED',
    ADD_FOLLOW:'ADD_FOLLOW',
    INCREASE_NOTICE_COUNT:'INCREASE_NOTICE_COUNT',
    INCREASE_NOTICE_UNREAD:'INCREASE_NOTICE_UNREAD',
    INCREASE_NOTICE_PAGE:'INCREASE_NOTICE_PAGE',
    ADD_EXISTS_NOTICE_RECORD:'ADD_EXISTS_NOTICE_RECORD',
    CLEAR_TWEETED_NOTICE:'CLEAR_TWEETED_NOTICE',
    SET_NOTICE_BOTTOM:'SET_NOTICE_BOTTOM',
}
export const e2eeMutations={
    SET_E2EE_PRIME:'SET_E2EE_PRIME',
    SET_E2EE_GENERATOR:'SET_E2EE_GENERATOR',
    ADD_E2EE_PUBLIC_KEY:'ADD_E2EE_PUBLIC_KEY',
    SET_E2EE_PRIVATE_KEY:'SET_E2EE_PRIVATE_KEY'
}
export const wsMutations={
    SET_WS:'SET_WS',
    SET_WS_URL:'SET_WS_URL',
    SET_WS_STATUS:'SET_WS_STATUS',
    PUSH_MSG_QUEUE:'PUSH_MSG_QUEUE',
    SHIFT_MSG_QUEUE:'SHIFT_MSG_QUEUE',
}
export const settingMutations={
    SET_CHAT_PINNED:'SET_CHAT_PINNED',
    SET_CHAT_ALLOW:'SET_CHAT_ALLOW'
}
export const chatMutations={
    ADD_CHAT_RECORD:'ADD_CHAT_RECORD',
    SET_CHAT_SHARE_KEY:'SET_CHAT_SHARE_KEY',
    INCREASE_CHAT_PAGE:'INCREASE_CHAT_PAGE',
    SET_CHAT_READING:'SET_CHAT_READING',
    SET_CHAT_REPLY:'SET_CHAT_REPLY',
    INCREASE_CHAT_COUNT:'INCREASE_CHAT_COUNT',
    INCREASE_CHAT_UNREAD:'INCREASE_CHAT_UNREAD',
    INCREASE_CONVERSATION_UNREAD:'INCREASE_CONVERSATION_UNREAD',
    ADD_CHAT_EXISTS_RECORD:'ADD_CHAT_EXISTS_RECORD',
    ADD_CHAT_ADVICE:'ADD_CHAT_ADVICE',
    SET_CONVERSATION_DATE:'SET_CONVERSATION_DATE',
    MODIFY_TEMP_CHAT:'MODIFY_TEMP_CHAT',
    SET_CONVERSATION_UNREAD:'SET_CONVERSATION_UNREAD',
    INIT_CONVERSATION:'INIT_CONVERSATION',
    SET_CHAT_LOAD_COMPLETE:'SET_CHAT_LOAD_COMPLETE',
    DEL_CHAT_RECORD:'DEL_CHAT_RECORD',
    CLEAR_CONVERSATION:'CLEAR_CONVERSATION',
    SET_CHAT_UNREAD:'SET_CHAT_UNREAD',
}